spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Users
    web:
      pageable:
        default-page-size: 50
        max-page-size: 1000
    redis:
      repositories:
        enabled: false
  application:
    name: spring-ss-product
  web:
    locale: ko_KR
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 128
        jdbc.batch_size: 128
        order_inserts: true
        order_updates: true
        connection:
          release_mode: on_close
          provider_disables_autocommit: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.url}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 5
      auto-commit: false
      pool-name: HikariCP
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

springdoc:
  swagger-ui:
    path: swagger.html
  paths-to-match:
    - /**


server:
  port: 9001
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR


---

spring:
  config:
    activate:
      on-profile: dev
database:
  url: jdbc:mysql://localhost:3306/boot3User?autoReconnect=true&useSSL=false

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: prod
database:
  url: jdbc:mysql://localhost:3306/boot3User?autoReconnect=true&useSSL=false

logging:
  level:
    org.hibernate.SQL: debug
